### ISSUE TITLE
cnf-cert pre-run fails if ginkgo is not installed.

### ISSUE THREAD

**Issue by colonwq** [redhat-cip/dci-openshift-app-agent#3]
The building of the cnf tests fails if the ginkgo tool is not available. 

This tool is not provided by the[ go-toolset package](https://github.com/redhat-cip/dci-openshift-app-agent/blob/master/roles/cnf-cert/tasks/pre-run.yml#L6). 

The test-network-function Makefile provides [install-tools](https://github.com/test-network-function/test-network-function/blob/a05750a40cce99dc154e79197ff57430377f786d/Makefile#L135) and [update-deps](https://github.com/test-network-function/test-network-function/blob/a05750a40cce99dc154e79197ff57430377f786d/Makefile#L129) targets. 

These may need to be added prior to calling the [build-cnf-test](https://github.com/redhat-cip/dci-openshift-app-agent/blob/master/roles/cnf-cert/tasks/pre-run.yml#L54)

**Comment by ramperher** [comment]
This issue is currently fixed, as Ginkgo is installed: https://github.com/redhat-cip/dci-openshift-app-agent/blob/master/roles/cnf-cert/tasks/pre-run.yml#L11

In any case, for future changes, you have to use the dci-openshift-app-agent repository from our Software Factory repository, under Gerrit: https://softwarefactory-project.io/r/admin/repos/dci-openshift-app-agent
